// Admin Audit Logs Console [integration] Test Skeleton
// Design Doc: admin-audit-logs-console-backend-design.md
// Frontend Design Doc: admin-audit-logs-console-frontend-design.md
// UI Spec: admin-audit-logs-console-ui-spec.md | PRD: admin-audit-logs-console-prd.md
// Generated: 2026-08-19 | Budget Used: integration 3/3 (this file), fixture-e2e 1/3 (sopet-admin), service-e2e 1/2
//
// Run:
//   yarn jest --config ./test/jest-e2e.json --testRegex='admin-audit-logs-console.int.test.ts$' --no-coverage
//
// Implement target: keep this file comment-only until the implementing task adds Nest TestingModule
// blocks. Unit Jest (`.*\\.spec\\.ts$`) does not collect this path. Promote executable coverage to
// `test/admin-audit-logs-console.service.e2e.test.ts` / `.e2e-spec.ts` when real Postgres is required.
//
// Covers (priority ACs):
//   log() dual-write requestId column + metadata.requestId
//   findAllForAdmin requestId equality filter (column, not JSON ILIKE) + existing filters + take cap
//   approveStoreReactivationRequest dual actions vs reject skip of reactivate
//   Retention processor loop: purgeExpired cutoff 60d, batch 1000, stop at 0
//
// Harness: Nest TestingModule + real AuditLogsService (+ reactivation resolver path for test 2,
// AuditLogRetentionProcessor for test 3); mocked TypeORM Repository<AuditLog> / fake query builder;
// real StoreReactivationRequestService with mocked TypeORM repos; StoresService.reactivate spy/stub
// that writes store.reactivated via real AuditLogsService; mocked BullMQ queue.
//
// Test Boundaries compliance (Backend Design Doc "Mock Boundary Decisions"):
// Mock: Repository<AuditLog> — service logic and query-builder clauses
// Mock: BullMQ / Redis — processor calls service; scheduler not asserted here
// Mock: Feature services (taxonomy/promotions/etc.) — writer families pushed to resolver unit specs
// @real-dependency: AuditLogsService.log / findAllForAdmin / purgeExpired
// @real-dependency: getAuditRequestContext (pure helper; plain req objects — do not mock)
// PostgreSQL engine: mocked at this lane (real DELETE/filter proven in service-integration-e2e)
//
// Dedup / push-down notes:
//   Existing audit-logs.service.spec.ts: persist, swallow save errors (AC-B-024), action/resource/
//     actor/search filters — keep; this file adds requestId dual-write, equality andWhere, purge.
//   Existing audit-logs.resolver.spec.ts (D010): pagination mapping without requestId — extend in
//     unit when mapper ships; GraphQL field presence is service-e2e.
//   Existing admin-team.resolver.spec.ts: admin-team writers — do not re-test here (AC-B-010).
//   AC-B-001/002/003/004/005/006/007/009 writer families → resolver unit tests (log once / skip /
//     no secret). Representative dual-action path is AC-B-008 only.
//   AC-B-011 schema/index → migration SQL review [IMPLEMENTATION_DETAIL]
//   AC-B-012 GraphQL requestId field → service-e2e + schema.gql
//   AC-B-014 ip helper branches → getAuditRequestContext unit tests [UNIT_LEVEL]
//   AC-B-017 no subscription → static [IMPLEMENTATION_DETAIL]
//   AC-B-019 Redis unset boot no-op → module/scheduler unit [UNIT_LEVEL]
//   AC-B-022 @Roles('admin') → decorator unit + service-e2e behavioral deny
//   AC-B-023 interceptor unregistered → app.module static + helper unit [UNIT_LEVEL]
//
// ---------------------------------------------------------------------------
// Integration test 1 of 3 — Dual-write requestId + equality filter + pagination cap
// ---------------------------------------------------------------------------
//
// AC-B-013: "When AdminAuditLogFilterInput.requestId is provided, findAllForAdmin shall add
// log.requestId = :requestId (equality). When omitted, the system shall not filter by request id."
// AC-B-015: "When a request id is available (header, req.requestId, or uuid generated by the
// helper), log shall persist the same value on column request_id and metadata.requestId."
// AC-B-016: "adminAuditLogs shall keep default limit=20 and server cap 100 (Math.min(limit, 100))."
// AC-B-021: "findAllForAdmin shall continue to orderBy createdAt DESC with skip/take and, when
// filtering by requestId, use the request_id column (not JSON text)."
// ROI: 120 (BV:10 × Freq:10 + Legal:true×10 + Defect:10)
// Behavior: log({ requestId, metadata }) → repository.create payload has requestId on the entity
// and metadata.requestId equal to the same string; findAllForAdmin(1, 20, { action, requestId })
// adds equality andWhere on log.requestId without dropping existing action andWhere; omitted
// requestId adds no requestId clause; findAllForAdmin(1, 500) takes 100.
// @category: core-functionality
// @lane: integration
// @dependency: AuditLogsService, Repository<AuditLog> (mocked), getAuditRequestContext (real)
// @complexity: high
// Primary failure mode: requestId stored only in jsonb metadata (or only on the column) so the
// indexed equality filter misses rows; or filter uses CAST(metadata AS TEXT) / ILIKE; or take
// becomes unbounded when limit > 100.
// Proof obligation: (1) Call log with requestId 'req-abc' and metadata { storeName: 'X' }; assert
// create payload requestId === 'req-abc' and metadata.requestId === 'req-abc' and storeName kept.
// (2) Fake query builder: filter { action: 'auth.login', requestId: 'req-abc' } → andWhere includes
// equality on log.requestId / :requestId and still includes the action clause; orderBy createdAt
// DESC; take 20. (3) Same listing without requestId → no requestId andWhere. (4) limit 500 → take
// 100. Boundary path: requestId present vs omitted (filter branch). Mock repo/query builder only.
// Verification points / expected results / pass criteria:
//   - create payload contains requestId column value and metadata.requestId as the same literal
//   - andWhere called with equality on requestId when filter.requestId is set
//   - andWhere for existing action filter still occurs (output-comparison fixture)
//   - omitted requestId does not add a requestId clause
//   - take is 20 for default and 100 when caller asks for 500
//   - Fail if ILIKE/JSON text used for the dedicated filter, dual-write missing either side, or take > 100
//
// ---------------------------------------------------------------------------
// Integration test 2 of 3 — Reactivation approve dual actions / reject does not reactivate
// ---------------------------------------------------------------------------
//
// AC-B-008: "When approveStoreReactivationRequest succeeds, the system shall write
// store.reactivation_approved (resourceType=reactivation_request, resourceId = request uuid,
// metadata.reactivationRequestId = request id, metadata.storeId = store id) and the existing
// store.reactivated row from storesService.reactivate shall still be written (two different
// actions, not duplicates of the same action). When rejectStoreReactivationRequest succeeds,
// the system shall write store.reactivation_rejected and shall not call reactivate."
// ROI: 70 (BV:10 × Freq:5 + Legal:true×10 + Defect:10)
// Behavior: admin approve success → AuditLogsService.log called for store.reactivation_approved
// with reactivation_request resource + request/store ids in metadata, and storesService.reactivate
// still runs (existing store.reactivated writer). Reject success → store.reactivation_rejected
// only; reactivate not called.
// @category: core-functionality
// @lane: integration
// @dependency: stores reactivation GraphQL path, real StoreReactivationRequestService (TypeORM
// repos mocked), StoresService.reactivate (spy/stub → real AuditLogsService), AuditLogsService
// (real), Repository<AuditLog> (mocked)
// @complexity: high
// Primary failure mode: approve replaces store.reactivated with the namespaced action (ops lose
// the existing store event), or approve writes two store.reactivated rows, or reject still calls
// reactivate / writes the approved action.
// Proof obligation: Arrange seeded request id + store id; act approve → captured log creates
// include exactly one store.reactivation_approved (resourceType reactivation_request, resourceId
// request uuid, metadata.reactivationRequestId + storeId) and exactly one store.reactivated;
// reactivate called once. Act reject on a pending request → exactly one store.reactivation_rejected;
// reactivate not called. Boundary path: reject must not take the approve/reactivate branch.
// Mock domain persist; do not mock AuditLogsService.
// Verification points / expected results / pass criteria:
//   - Approve: two distinct actions present (reactivation_approved + reactivated)
//   - Approve: resourceId is request uuid; metadata includes reactivationRequestId and storeId
//   - Reject: only store.reactivation_rejected; reactivate spy not called
//   - Fail if approve omits store.reactivated, duplicates it, or reject reactivates
//
// ---------------------------------------------------------------------------
// Integration test 3 of 3 — Retention processor batched purge cutoff
// ---------------------------------------------------------------------------
//
// AC-B-018: "When Redis is configured, a BullMQ repeatable job purge-expired-audit-logs on queue
// audit-log-retention shall hard-delete audit_logs where created_at < now() - retentionDays
// (default 60) in batches of 1000, looping until a batch deletes 0 rows. Schedule: 0 3 * * *
// Asia/Bangkok (20:00 UTC). Processor concurrency 1."
// AC-B-020: "Retention delete shall target only rows older than 60 days (or configured
// AUDIT_LOG_RETENTION_DAYS) and leave newer rows intact. Processor failures shall be
// logger.error'd (no silent fail-open)."
// ROI: 70 (BV:10 × Freq:5 + Legal:true×10 + Defect:10)
// Behavior: AuditLogRetentionProcessor handles purge-expired-audit-logs → loops AuditLogsService.purgeExpired
// (cutoff ≈ now-60d, limit 1000) until a batch returns 0; a 61-day-old row is in the delete set and
// a 1-day-old row is not; processor error is logged and rethrown (not swallowed).
// @category: core-functionality
// @lane: integration
// @dependency: AuditLogRetentionProcessor, AuditLogsService.purgeExpired, Repository<AuditLog>
// (fake delete capturing WHERE cutoff), Logger
// @complexity: high
// Primary failure mode: unbounded DELETE or cutoff inclusive of now so recent investigation rows
// disappear; or processor swallows errors (silent fail-open) so ops never see a stuck purge.
// Proof obligation: Fake repo: first purgeExpired returns 1000, second returns 0 → processor stops
// after the zero batch; captured cutoff Date is ~60 days before frozen now (not now, not 59d);
// delete predicate would include created_at 61d ago and exclude 1d ago. Throw from purgeExpired →
// logger.error called and error propagates. Boundary path: loop termination at deleted-count 0;
// newer-than-cutoff rows must remain. Mock repo/BullMQ; real processor + service.
// Real SQL DELETE locking is out of this lane (service-integration-e2e).
// Verification points / expected results / pass criteria:
//   - Processor invokes purgeExpired with limit 1000 and cutoff ≈ now - 60 days
//   - Loop stops when a batch deletes 0 rows (no infinite loop)
//   - 61-day-old row eligible; 1-day-old row not eligible
//   - On purgeExpired throw: logger.error and rethrow (not resolve undefined)
//   - Fail if DELETE has no cutoff, batch size unbounded, or errors are swallowed

import { Logger } from '@nestjs/common';
import { getRepositoryToken } from '@nestjs/typeorm';
import { Test, TestingModule } from '@nestjs/testing';
import { Job } from 'bullmq';
import { AuditLog, AuditActorType } from '../src/database/entities/audit-log.entity';
import { AuditLogsService } from '../src/modules/audit-logs/audit-logs.service';
import { getAuditRequestContext } from '../src/modules/audit-logs/audit-request-context';
import { AuditLogRetentionProcessor } from '../src/modules/audit-logs/audit-log-retention.processor';
import { AuditLogRetentionService } from '../src/modules/audit-logs/audit-log-retention.service';
import {
  AUDIT_LOG_RETENTION_BATCH_SIZE,
  AUDIT_LOG_RETENTION_JOB,
} from '../src/modules/audit-logs/audit-log-retention.constants';
import { AuditAction, AuditResourceType } from '../src/modules/audit-logs/audit-log.constants';
import { StoresResolver } from '../src/modules/stores/stores.resolver';
import { StoresService } from '../src/modules/stores/stores.service';
import { StoreTeamService } from '../src/modules/stores/store-team.service';
import { ShippingOptionsService } from '../src/modules/stores/shipping-options.service';
import { ShippingProvidersService } from '../src/modules/stores/shipping-providers.service';
import { StoreRequestService } from '../src/modules/stores/store-request.service';
import { StoreReactivationRequestService } from '../src/modules/stores/store-reactivation-request.service';
import { VendorInvitationService } from '../src/modules/stores/vendor-invitation.service';
import { AuthService } from '../src/modules/auth/auth.service';
import { StoreReactivationRequestStatus } from '../src/database/entities/store-reactivation-request.entity';
import type { GraphqlContext } from '../src/graphql/loaders/graphql-context.types';

type FakeQueryBuilder = {
  orderBy: jest.Mock;
  skip: jest.Mock;
  take: jest.Mock;
  andWhere: jest.Mock;
  getManyAndCount: jest.Mock;
};

function createFakeQueryBuilder(): FakeQueryBuilder {
  const qb: FakeQueryBuilder = {
    orderBy: jest.fn().mockReturnThis(),
    skip: jest.fn().mockReturnThis(),
    take: jest.fn().mockReturnThis(),
    andWhere: jest.fn().mockReturnThis(),
    getManyAndCount: jest.fn().mockResolvedValue([[], 0]),
  };
  return qb;
}

type CreatePayload = {
  requestId: string;
  metadata: { requestId: string; storeName?: string };
};

describe('admin-audit-logs-console integration', () => {
  let service: AuditLogsService;
  let createCalls: CreatePayload[];
  let auditLogRepo: {
    create: jest.Mock;
    save: jest.Mock;
    createQueryBuilder: jest.Mock;
  };

  beforeEach(async () => {
    createCalls = [];
    auditLogRepo = {
      create: jest.fn((x: CreatePayload) => {
        createCalls.push(x);
        return x;
      }),
      save: jest.fn((x: Record<string, unknown>) => Promise.resolve({ ...x, id: 'log-int-1' })),
      createQueryBuilder: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AuditLogsService,
        { provide: getRepositoryToken(AuditLog), useValue: auditLogRepo },
      ],
    }).compile();

    service = module.get(AuditLogsService);
  });

  // Integration test 1 — Dual-write requestId + equality filter + pagination cap
  // Primary failure mode: requestId only in jsonb (or only column); ILIKE/CAST metadata for
  // dedicated filter; take unbounded when limit > 100.
  it('dual-writes requestId, filters with column equality, and caps take at 100', async () => {
    // (1) Dual-write + roundtrip: column === metadata.requestId === 'req-abc'; storeName kept
    await service.log({
      actorType: AuditActorType.ADMIN,
      actorId: 'admin-1',
      action: 'auth.login',
      resourceType: 'user',
      requestId: 'req-abc',
      metadata: { storeName: 'X' },
    });

    expect(auditLogRepo.create).toHaveBeenCalledWith(
      expect.objectContaining({
        requestId: 'req-abc',
        metadata: {
          requestId: 'req-abc',
          storeName: 'X',
        },
      }),
    );
    const created = createCalls[0];
    expect(created.requestId).toBe('req-abc');
    expect(created.metadata.requestId).toBe('req-abc');
    expect(created.requestId).toBe(created.metadata.requestId);
    expect(created.metadata.storeName).toBe('X');

    // Real getAuditRequestContext (not mocked) → same dual-write path
    const ctx = getAuditRequestContext({
      headers: { 'x-request-id': 'req-from-helper' },
    });
    expect(ctx.requestId).toBe('req-from-helper');
    await service.log({
      actorType: AuditActorType.ADMIN,
      action: 'auth.login',
      resourceType: 'user',
      requestId: ctx.requestId,
      metadata: { storeName: 'Y' },
    });
    const helperCreated = createCalls[1];
    expect(helperCreated.requestId).toBe(helperCreated.metadata.requestId);
    expect(helperCreated.requestId).toBe('req-from-helper');

    // (2) Equality filter on column + existing action clause; orderBy DESC; take 20
    const qbWithRequestId = createFakeQueryBuilder();
    auditLogRepo.createQueryBuilder.mockReturnValue(qbWithRequestId);

    await service.findAllForAdmin(1, 20, {
      action: 'auth.login',
      requestId: 'req-abc',
    });

    expect(qbWithRequestId.andWhere).toHaveBeenCalledWith('log.action = :action', {
      action: 'auth.login',
    });
    expect(qbWithRequestId.andWhere).toHaveBeenCalledWith('log.requestId = :requestId', {
      requestId: 'req-abc',
    });
    const clausesWithId = qbWithRequestId.andWhere.mock.calls.map((c: unknown[]) => String(c[0]));
    expect(clausesWithId.some((c: string) => /ILIKE/i.test(c) && /requestId/i.test(c))).toBe(false);
    expect(
      clausesWithId.some((c: string) => /CAST\(log\.metadata/i.test(c) && /requestId/i.test(c)),
    ).toBe(false);
    expect(qbWithRequestId.orderBy).toHaveBeenCalledWith('log.createdAt', 'DESC');
    expect(qbWithRequestId.take).toHaveBeenCalledWith(20);
    expect(qbWithRequestId.skip).toHaveBeenCalledWith(0);

    // (3) Omitted requestId → no requestId andWhere
    const qbWithoutRequestId = createFakeQueryBuilder();
    auditLogRepo.createQueryBuilder.mockReturnValue(qbWithoutRequestId);

    await service.findAllForAdmin(1, 20, { action: 'auth.login' });

    const clausesWithoutId = qbWithoutRequestId.andWhere.mock.calls.map((c: unknown[]) =>
      String(c[0]),
    );
    expect(clausesWithoutId.some((c: string) => c.includes('log.requestId'))).toBe(false);
    expect(qbWithoutRequestId.andWhere).toHaveBeenCalledWith('log.action = :action', {
      action: 'auth.login',
    });
    expect(qbWithoutRequestId.orderBy).toHaveBeenCalledWith('log.createdAt', 'DESC');
    expect(qbWithoutRequestId.take).toHaveBeenCalledWith(20);

    // (4) limit 500 → take 100 (cap); requestId equality still applied
    const qbCapped = createFakeQueryBuilder();
    auditLogRepo.createQueryBuilder.mockReturnValue(qbCapped);

    await service.findAllForAdmin(1, 500, { requestId: 'req-abc' });

    expect(qbCapped.take).toHaveBeenCalledWith(100);
    expect(qbCapped.take.mock.calls.every((c: unknown[]) => Number(c[0]) <= 100)).toBe(true);
    expect(qbCapped.orderBy).toHaveBeenCalledWith('log.createdAt', 'DESC');
    expect(qbCapped.andWhere).toHaveBeenCalledWith('log.requestId = :requestId', {
      requestId: 'req-abc',
    });
  });

  // Integration test 2 of 3 — Reactivation approve dual actions / reject does not reactivate
  // Primary failure mode: approve replaces store.reactivated with namespaced action, or writes two
  // store.reactivated rows, or reject still calls reactivate / writes the approved action.
  // TypeORM persist is mocked because this lane proves writer composition, not SQL.
  describe('reactivation approve dual actions / reject does not reactivate', () => {
    const REQUEST_ID = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
    const STORE_ID = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
    const ADMIN_ID = 'cccccccc-cccc-4ccc-8ccc-cccccccccccc';
    const ADMIN_EMAIL = 'admin@sopet.org';

    const graphqlContext: GraphqlContext = {
      req: { requestId: 'req-reactivation-1', headers: { 'x-forwarded-for': '203.0.113.77' } },
      res: {},
      loaders: { productSoldCount: { load: jest.fn() } as never },
    };

    type LogCreatePayload = {
      action: string;
      resourceType: string;
      resourceId: string | null;
      metadata: Record<string, unknown>;
    };

    let resolver: StoresResolver;
    let reactivate: jest.Mock;
    let logCreates: LogCreatePayload[];

    const seededPendingRequest = {
      id: REQUEST_ID,
      storeId: STORE_ID,
      store: { name: 'Suspended Pets' },
      submittedByUserId: 'vendor-1',
      title: 'Please reopen',
      content: 'We resolved the issues',
      status: StoreReactivationRequestStatus.PENDING,
      reviewNote: null as string | null,
      images: [] as unknown[],
      createdAt: new Date('2026-01-01T00:00:00Z'),
      updatedAt: new Date('2026-01-01T00:00:00Z'),
      reviewedAt: null as Date | null,
      reviewedBy: null as string | null,
    };

    beforeEach(async () => {
      logCreates = [];
      const auditLogRepo = {
        create: jest.fn((x: LogCreatePayload) => {
          logCreates.push(x);
          return x;
        }),
        save: jest.fn((x: Record<string, unknown>) => Promise.resolve({ ...x, id: 'log-int-2' })),
        createQueryBuilder: jest.fn(),
      };

      const module: TestingModule = await Test.createTestingModule({
        providers: [
          AuditLogsService,
          { provide: getRepositoryToken(AuditLog), useValue: auditLogRepo },
        ],
      }).compile();

      const auditLogsService = module.get(AuditLogsService);

      // Spy/stub: production StoresService.reactivate writes store.reactivated via AuditLogsService.
      reactivate = jest.fn().mockImplementation(async (storeId: string, adminId: string) => {
        await auditLogsService.log({
          actorType: AuditActorType.ADMIN,
          actorId: adminId,
          action: AuditAction.STORE_REACTIVATED,
          resourceType: AuditResourceType.STORE,
          resourceId: storeId,
          metadata: { storeName: 'Suspended Pets' },
        });
        return { id: storeId, name: 'Suspended Pets', status: 'approved' };
      });

      const requestRepo = {
        findOne: jest.fn().mockImplementation((options: { where?: { id?: string } }) => {
          if (options?.where?.id === REQUEST_ID) {
            return Promise.resolve({ ...seededPendingRequest });
          }
          return Promise.resolve(null);
        }),
        save: jest.fn((entity: typeof seededPendingRequest) => Promise.resolve({ ...entity })),
        create: jest.fn(),
        find: jest.fn(),
      };
      const imageRepo = { create: jest.fn(), save: jest.fn() };
      const storeRepo = { findOne: jest.fn() };

      // Real StoreReactivationRequestService: approve calls storesService.reactivate; reject does not.
      const reactivationService = new StoreReactivationRequestService(
        requestRepo as never,
        imageRepo as never,
        storeRepo as never,
        { reactivate } as unknown as StoresService,
      );

      resolver = new StoresResolver(
        { reactivate } as unknown as StoresService,
        {} as StoreTeamService,
        {} as ShippingOptionsService,
        {} as ShippingProvidersService,
        {} as StoreRequestService,
        reactivationService,
        {} as VendorInvitationService,
        {} as AuthService,
        auditLogsService,
      );
    });

    it('approve writes one store.reactivation_approved and one store.reactivated (distinct actions)', async () => {
      await resolver.approveStoreReactivationRequest(
        REQUEST_ID,
        ADMIN_ID,
        ADMIN_EMAIL,
        graphqlContext,
      );

      expect(reactivate).toHaveBeenCalledTimes(1);
      expect(reactivate).toHaveBeenCalledWith(STORE_ID, ADMIN_ID);

      const approvedRows = logCreates.filter(
        (row) => row.action === AuditAction.STORE_REACTIVATION_APPROVED,
      );
      const reactivatedRows = logCreates.filter(
        (row) => row.action === AuditAction.STORE_REACTIVATED,
      );
      expect(approvedRows).toHaveLength(1);
      expect(reactivatedRows).toHaveLength(1);
      expect(logCreates).toHaveLength(2);
      expect(approvedRows[0].action).not.toBe(reactivatedRows[0].action);

      expect(approvedRows[0].resourceType).toBe(AuditResourceType.REACTIVATION_REQUEST);
      expect(approvedRows[0].resourceId).toBe(REQUEST_ID);
      expect(approvedRows[0].metadata.reactivationRequestId).toBe(REQUEST_ID);
      expect(approvedRows[0].metadata.storeId).toBe(STORE_ID);

      expect(reactivatedRows[0].resourceType).toBe(AuditResourceType.STORE);
      expect(reactivatedRows[0].resourceId).toBe(STORE_ID);
    });

    it('reject writes store.reactivation_rejected only and does not call reactivate', async () => {
      await resolver.rejectStoreReactivationRequest(
        { id: REQUEST_ID, reviewNote: 'Incomplete documents' },
        ADMIN_ID,
        ADMIN_EMAIL,
        graphqlContext,
      );

      expect(reactivate).not.toHaveBeenCalled();
      expect(logCreates).toHaveLength(1);
      expect(logCreates[0].action).toBe(AuditAction.STORE_REACTIVATION_REJECTED);
      expect(logCreates[0].resourceType).toBe(AuditResourceType.REACTIVATION_REQUEST);
      expect(logCreates[0].resourceId).toBe(REQUEST_ID);
      expect(logCreates[0].metadata.reactivationRequestId).toBe(REQUEST_ID);
      expect(logCreates[0].metadata.storeId).toBe(STORE_ID);
      expect(logCreates.map((row) => row.action)).not.toContain(
        AuditAction.STORE_REACTIVATION_APPROVED,
      );
      expect(logCreates.map((row) => row.action)).not.toContain(AuditAction.STORE_REACTIVATED);
    });
  });

  // Integration test 3 of 3 — Retention processor batched purge cutoff
  // Primary failure mode: unbounded DELETE or cutoff inclusive of now; or processor swallows errors.
  describe('retention processor batched purge cutoff', () => {
    const MS_PER_DAY = 24 * 60 * 60 * 1000;

    type DeleteQueryBuilder = {
      delete: jest.Mock;
      from: jest.Mock;
      where: jest.Mock;
      execute: jest.Mock;
    };

    let processor: AuditLogRetentionProcessor;
    let deleteQb: DeleteQueryBuilder;
    let capturedCutoffs: Date[];
    let executeAffectedQueue: number[];
    let executeRejectOnce: Error | null;
    let errorSpy: jest.SpyInstance;

    beforeEach(async () => {
      capturedCutoffs = [];
      executeAffectedQueue = [1000, 0];
      executeRejectOnce = null;
      let executeCall = 0;

      deleteQb = {
        delete: jest.fn().mockReturnThis(),
        from: jest.fn().mockReturnThis(),
        where: jest
          .fn()
          .mockImplementation((_sql: string, params: { cutoff: Date; limit: number }) => {
            capturedCutoffs.push(params.cutoff);
            return deleteQb;
          }),
        execute: jest.fn().mockImplementation(() => {
          if (executeRejectOnce) {
            const err = executeRejectOnce;
            executeRejectOnce = null;
            return Promise.reject(err);
          }
          const affected =
            executeAffectedQueue[Math.min(executeCall, executeAffectedQueue.length - 1)] ?? 0;
          executeCall += 1;
          return Promise.resolve({ affected });
        }),
      };

      const retentionRepo = {
        create: jest.fn(),
        save: jest.fn(),
        createQueryBuilder: jest.fn().mockReturnValue(deleteQb),
      };

      const retentionService = {
        resolveRetentionDays: jest.fn().mockReturnValue(60),
      };

      const module: TestingModule = await Test.createTestingModule({
        providers: [
          AuditLogsService,
          AuditLogRetentionProcessor,
          { provide: getRepositoryToken(AuditLog), useValue: retentionRepo },
          { provide: AuditLogRetentionService, useValue: retentionService },
        ],
      }).compile();

      processor = module.get(AuditLogRetentionProcessor);
      errorSpy = jest.spyOn(Logger.prototype, 'error').mockImplementation(() => undefined);
    });

    afterEach(() => {
      errorSpy.mockRestore();
      jest.useRealTimers();
    });

    it('loops purgeExpired with ~60d cutoff; 61d eligible / 1d intact; stops at deleted=0', async () => {
      const frozenNow = new Date('2026-08-19T10:00:00.000Z');
      jest.useFakeTimers({ now: frozenNow });

      await processor.process({ name: AUDIT_LOG_RETENTION_JOB } as Job);

      // Loop: first batch 1000, second 0 → stop (two purgeExpired / execute calls)
      expect(deleteQb.execute).toHaveBeenCalledTimes(2);
      expect(capturedCutoffs).toHaveLength(2);

      const expectedCutoff = new Date(frozenNow.getTime() - 60 * MS_PER_DAY);
      const cutoff = capturedCutoffs[0];
      expect(cutoff.getTime()).toBe(expectedCutoff.getTime());
      // Not now, not 59d
      expect(cutoff.getTime()).not.toBe(frozenNow.getTime());
      expect(cutoff.getTime()).not.toBe(frozenNow.getTime() - 59 * MS_PER_DAY);
      expect(Math.abs(frozenNow.getTime() - cutoff.getTime() - 60 * MS_PER_DAY)).toBe(0);

      const whereCall = deleteQb.where.mock.calls[0] as [string, { cutoff: Date; limit: number }];
      const whereSql = String(whereCall[0]);
      expect(whereSql).toMatch(/created_at\s*<\s*:cutoff/i);
      expect(whereSql).not.toMatch(/created_at\s*<=\s*:cutoff/i);
      expect(whereCall[1].limit).toBe(AUDIT_LOG_RETENTION_BATCH_SIZE);
      expect(AUDIT_LOG_RETENTION_BATCH_SIZE).toBe(1000);

      // Delete predicate eligibility: 61d in set; 1d not in set
      const eligible61d = new Date(frozenNow.getTime() - 61 * MS_PER_DAY);
      const intact1d = new Date(frozenNow.getTime() - 1 * MS_PER_DAY);
      expect(eligible61d.getTime()).toBeLessThan(cutoff.getTime());
      expect(intact1d.getTime()).toBeGreaterThanOrEqual(cutoff.getTime());
    });

    it('logs error and rethrows when purgeExpired fails (no silent fail-open)', async () => {
      const boom = new Error('db delete failed');
      executeRejectOnce = boom;

      await expect(processor.process({ name: AUDIT_LOG_RETENTION_JOB } as Job)).rejects.toThrow(
        'db delete failed',
      );

      expect(errorSpy).toHaveBeenCalledWith(
        expect.stringMatching(/Audit log retention purge failed/i),
        expect.any(String),
      );
    });
  });
});
